### ISSUE TITLE
Remove e navigation option for selections without any items

### ISSUE THREAD

**Issue by sh3r4rd** [jacobmoe/nltui#4]
The `e` options allows you to enter a selection that contains items.  But for selections without items, the `e` options doesn't have any effect/you can't use it.  We should probably remove that `e` when the user is on an input option without a list of needs.

**Comment by jacobmoe** [comment]
Resolved in https://github.com/jacobmoe/nltui/commit/a6b184659efa77560607564ca35b34a77028253a
